[package]
name = "exgui_renderer_nanovg"
version = "0.1.0"

[dependencies]
nanovg = { version = "1.0", features = ["gl3"] }
exgui = { git = "https://github.com/exgui/exgui.git" }

[dev-dependencies]
glutin = "0.13"
gl = "0.10"
chrono = "0.4"
rand = "0.4"
lazy_static = "1.0"
